spring.application.name=SpringProject_Authentification
jwt.secret=mY7Gx2Kp9QwL4nZr8Vt1Hs6Du3Ef0AbCdEfGhIjKlMnOpQrS=
jwt.expiration=3600000
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=project
spring.jpa.hibernate.ddl-auto=update
